### PR TITLE
Add bower.json

### PR DESCRIPTION
**Pull request by nygdjs**
Created initial version of `bower.json`, as mentioned in issue #77. Bower.json is based on the projects `package.json` and the official [spec](https://github.com/bower/spec/blob/master/json.md). Both .js (unminified) and .css are included in main, so a fully working copy of Wallop will be available if these files are picked.

### CODE REVIEW

**Comment by peduarte** [comment]
Is this enough to solve your problem?

I swear I had a `bower.json` spec. Because you can install it from bower already. I just took a look at their [docs](https://bower.io/docs/creating-packages/) and it says that in order to create a package there **must** be a `bower.json` spec so I'm wondering how it's currently working? haha

You can see its currently available [here](https://bower.io/search/?q=wallop)

**Comment by nygdjs** [comment]
Honestly Im not entirely sure :), I got a bit confused, when realised that the project didn't have a `bower.json`, but still was available via bower. Will check how it was possible and see if its enough or not.
Sorry for the late reply, I dont have that much time these days, but will look into it further this week and let you know.

**Comment by peduarte** [comment]
No worries. I agree it's worth double checking to ensure we don't release a broken build.

👌

**Comment by nygdjs** [comment]
_Sorry for the delay..._
I looked into it, and still don't really know how it was possible, that the project doesn't have a `bower.json`, and still was available. :)
I think somehow it was just auto-generated, with the bare minimum only. I think (but not sure) we can just add `bower.json`, so it will be used after, instead of the "generated one".

But there is another thing... We and I suppose many others actively moving away from Bower in favor of **yarn** and **Webpack**. So Im not sure if it is that relevant any more. Whats your opinion?

**Comment by peduarte** [comment]
I don't think it's necessary either. I'd be happier to leave it as it is, but I'd be willing to add if it will help you *and* if you're sure of how to add it.

**Comment by nygdjs** [comment]
_Sorry for the delay..._
So... I think it's not necessary at this point either. And sorry for the fuss with it. Seemed more important a few weeks ago.

**Comment by peduarte** [comment]
No worries :)

**Pull request closed without merging**
